export const data = {
  user1: {
    name: 'John Doe',
    vroom: 'BYTECITY',
    profilePicture: 'https://i.ibb.co/Fq85sGjC/pngegg-2.png',
    photoUrl: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    username: 'johnte',
    description: 'Lorem ipsum dolor sit amet.',
  },
  user2: {
    name: 'Alan Smith',
    vroom: 'SAFRA INC',
    profilePicture: 'https://randomuser.me/api/portraits/men/32.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    username: 'alans',
    description: 'Lorem ipsum dolor sit amet.',
  },
  user3: {
    name: 'Emma Brown',
    vroom: 'ZENWORKS',
    profilePicture: 'https://randomuser.me/api/portraits/women/44.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    username: 'emmab',
    description: 'Consectetur adipiscing elit.',
  },
  user4: {
    name: 'Michael Johnson',
    vroom: 'NEOTASK',
    profilePicture: 'https://randomuser.me/api/portraits/men/56.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg',
    username: 'mikej',
    description: 'Sed do eiusmod tempor incididunt.',
  },
  user5: {
    name: 'Sophia Davis',
    vroom: 'CIRRIX LABS',
    profilePicture: 'https://randomuser.me/api/portraits/women/68.jpg',
    photoUrl: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
    username: 'sophiad',
    description: 'Ut labore et dolore magna aliqua.',
  },
  user6: {
    name: 'James Wilson',
    vroom: 'OMEGA DEV',
    profilePicture: 'https://randomuser.me/api/portraits/men/77.jpg',
    photoUrl: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
    username: 'jamesw',
    description: 'Quis nostrud exercitation ullamco.',
  },
  user7: {
    name: 'Olivia Martinez',
    vroom: 'VANTEX GROUP',
    profilePicture: 'https://randomuser.me/api/portraits/women/81.jpg',
    photoUrl: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
    username: 'oliviam',
    description: 'Laboris nisi ut aliquip ex ea commodo.',
  },
  user8: {
    name: 'William Garcia',
    vroom: 'NEXACO',
    profilePicture: 'https://randomuser.me/api/portraits/men/89.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg',
    username: 'willg',
    description: 'Duis aute irure dolor in reprehenderit.',
  },
  user9: {
    name: 'Ava Lee',
    vroom: 'QUANTIA',
    profilePicture: 'https://randomuser.me/api/portraits/women/90.jpg',
    photoUrl: 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg',
    username: 'avalee',
    description: 'Voluptate velit esse cillum dolore.',
  },
  user10: {
    name: 'David Clark',
    vroom: 'MOBYTECH',
    profilePicture: 'https://randomuser.me/api/portraits/men/95.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_UL640_QL65_ML3_.jpg',
    username: 'davidc',
    description: 'Eu fugiat nulla pariatur.',
  },
  user11: {
    name: 'Lily Walker',
    vroom: 'DYNALINK',
    profilePicture: 'https://randomuser.me/api/portraits/women/22.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    username: 'lilyw',
    description: 'Aliquam erat volutpat.',
  },
  user12: {
    name: 'Ethan Hall',
    vroom: 'ZENTEK',
    profilePicture: 'https://randomuser.me/api/portraits/men/23.jpg',
    photoUrl: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
    username: 'ethanh',
    description: 'Curabitur non nulla sit amet.',
  },
  user13: {
    name: 'Grace Moore',
    vroom: 'INNOVANA',
    profilePicture: 'https://randomuser.me/api/portraits/women/45.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    username: 'gracem',
    description: 'Bibendum sapien ac.',
  },
  user14: {
    name: 'Henry Allen',
    vroom: 'SYNAPTECH',
    profilePicture: 'https://randomuser.me/api/portraits/men/45.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_UL640_QL65_ML3_.jpg',
    username: 'henrya',
    description: 'Amet nisl suscipit adipiscing.',
  },
  user15: {
    name: 'Ella Scott',
    vroom: 'SKYPULSE',
    profilePicture: 'https://randomuser.me/api/portraits/women/52.jpg',
    photoUrl: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
    username: 'ellascott',
    description: 'Morbi tristique senectus.',
  },
  user16: {
    name: 'Liam King',
    vroom: 'NANOTRON',
    profilePicture: 'https://randomuser.me/api/portraits/men/49.jpg',
    photoUrl: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    username: 'liamk',
    description: 'Vestibulum ac diam sit amet.',
  },
  user17: {
    name: 'Chloe Adams',
    vroom: 'INFONIX',
    profilePicture: 'https://randomuser.me/api/portraits/women/54.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg',
    username: 'chloea',
    description: 'Mauris blandit aliquet elit.',
  },
  user18: {
    name: 'Mason Torres',
    vroom: 'PIXELHUB',
    profilePicture: 'https://randomuser.me/api/portraits/men/58.jpg',
    photoUrl: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
    username: 'masont',
    description: 'Cras ultricies ligula sed magna.',
  },
  user19: {
    name: 'Zoey Brooks',
    vroom: 'FLEXBYTE',
    profilePicture: 'https://randomuser.me/api/portraits/women/61.jpg',
    photoUrl: 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg',
    username: 'zoeyb',
    description: 'Donec rutrum congue leo.',
  },
  user20: {
    name: 'Noah Rivera',
    vroom: 'ORBITA',
    profilePicture: 'https://randomuser.me/api/portraits/men/63.jpg',
    photoUrl: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
    username: 'noahr',
    description: 'Quisque velit nisi.',
  },
  user21: {
    name: 'Layla Ramirez',
    vroom: 'STRATOPATH',
    profilePicture: 'https://randomuser.me/api/portraits/women/70.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    username: 'laylar',
    description: 'Vel facilisis volutpat est.',
  },
  user22: {
    name: 'Lucas Campbell',
    vroom: 'ZAPCORE',
    profilePicture: 'https://randomuser.me/api/portraits/men/72.jpg',
    photoUrl: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
    username: 'lucasc',
    description: 'Mauris eget velit consequat.',
  },
  user23: {
    name: 'Harper Evans',
    vroom: 'CLOUDRAIL',
    profilePicture: 'https://randomuser.me/api/portraits/women/73.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
    username: 'harpere',
    description: 'Nulla quis lorem ut libero.',
  },
  user24: {
    name: 'Logan Murphy',
    vroom: 'TECHSPHERE',
    profilePicture: 'https://randomuser.me/api/portraits/men/74.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg',
    username: 'loganm',
    description: 'Faucibus sed sapien.',
  },
  user25: {
    name: 'Scarlett Hughes',
    vroom: 'DREAMCORE',
    profilePicture: 'https://randomuser.me/api/portraits/women/75.jpg',
    photoUrl: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
    username: 'scarletth',
    description: 'Sed porttitor lectus nibh.',
  },
  user26: {
    name: 'Jackson Bell',
    vroom: 'TURBOWORKS',
    profilePicture: 'https://randomuser.me/api/portraits/men/76.jpg',
    photoUrl: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
    username: 'jacksonb',
    description: 'Cras ultricies ligula sed magna.',
  },
  user27: {
    name: 'Aria Foster',
    vroom: 'OPTICLOOP',
    profilePicture: 'https://randomuser.me/api/portraits/women/77.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_UL640_QL65_ML3_.jpg',
    username: 'ariaf',
    description: 'Vivamus magna justo lacinia.',
  },
  user28: {
    name: 'Benjamin Moore',
    vroom: 'NEXTBYTE',
    profilePicture: 'https://randomuser.me/api/portraits/men/78.jpg',
    photoUrl: 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg',
    username: 'benmoore',
    description: 'Curabitur arcu erat accumsan.',
  },
  user29: {
    name: 'Mila Reed',
    vroom: 'CODEVAULT',
    profilePicture: 'https://randomuser.me/api/portraits/women/79.jpg',
    photoUrl: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
    username: 'milareed',
    description: 'Sed porttitor lectus.',
  },
  user30: {
    name: 'Alexander Price',
    vroom: 'QUANTASY',
    profilePicture: 'https://randomuser.me/api/portraits/men/80.jpg',
    photoUrl: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
    username: 'alexp',
    description: 'Vestibulum ante ipsum primis.',
  },
};
